spring:
  datasource:
    url: jdbc:postgresql://localhost:5433/skillfactory?currentSchema=bank
    username: postgres
    password: postgres
  jpa:
    hibernate:
      ddl-auto: none
    show-sql: true


  flyway:
    user: postgres
    password: postgres
    url: jdbc:postgresql://localhost:5433/skillfactory
    default-schema: bank

server:
  port: 8082